"""init

Revision ID: 8fdcd798053a
Revises: 
Create Date: 2026-06-23 06:41:18.550114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fdcd798053a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_staff_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_slots_id'), 'shift_slots', ['id'], unique=False)
    op.create_index(op.f('ix_shift_slots_start_at'), 'shift_slots', ['start_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('shift_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['shift_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slot_id', name='uq_user_slot_assignment')
    )
    op.create_index(op.f('ix_shift_assignments_id'), 'shift_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_slot_id'), 'shift_assignments', ['slot_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_user_id'), 'shift_assignments', ['user_id'], unique=False)
    op.create_table('shift_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_slot_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('UNAVAILABLE', 'AVOID', 'NEUTRAL', 'PREFERRED', 'REQUIRED', name='preferencepriority'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shift_slot_id'], ['shift_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'shift_slot_id', name='uq_user_shift_preference')
    )
    op.create_index(op.f('ix_shift_preferences_id'), 'shift_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_shift_preferences_shift_slot_id'), 'shift_preferences', ['shift_slot_id'], unique=False)
    op.create_index(op.f('ix_shift_preferences_user_id'), 'shift_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_preferences_user_id'), table_name='shift_preferences')
    op.drop_index(op.f('ix_shift_preferences_shift_slot_id'), table_name='shift_preferences')
    op.drop_index(op.f('ix_shift_preferences_id'), table_name='shift_preferences')
    op.drop_table('shift_preferences')
    op.drop_index(op.f('ix_shift_assignments_user_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_slot_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_id'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shift_slots_start_at'), table_name='shift_slots')
    op.drop_index(op.f('ix_shift_slots_id'), table_name='shift_slots')
    op.drop_table('shift_slots')
    # ### end Alembic commands ###
