"""init

Revision ID: 95ef0430aa7f
Revises: 9089feb774b3
Create Date: 2026-04-27 02:39:36.586350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95ef0430aa7f'
down_revision: Union[str, Sequence[str], None] = '9089feb774b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_postings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'user_id')
    # ### end Alembic commands ###
