"""add user_id to shift_preferences

Revision ID: ea2a6147db9a
Revises: 70700a8a663d
Create Date: 2026-06-10 01:28:51.942382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2a6147db9a'
down_revision: Union[str, Sequence[str], None] = '70700a8a663d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_preferences', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_shift_preferences_user_id'), 'shift_preferences', ['user_id'], unique=False)
    op.create_foreign_key(None, 'shift_preferences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_preferences', type_='foreignkey')
    op.drop_index(op.f('ix_shift_preferences_user_id'), table_name='shift_preferences')
    op.drop_column('shift_preferences', 'user_id')
    # ### end Alembic commands ###

